VERSION = "0.9 Beta"

FEATURES = {
    "FastAPI": True,
    "DWD-Warnungen": True,
    "Deutschlandkarte": True,
    "Landkreissuche": True,
    "Radar": True,
    "Live-Wetterdaten": True,
    "Wind": True,
    "Windböen": True,
    "Niederschlag": True,
    "Luftfeuchtigkeit": True,
    "Luftdruck": True,
    "Gefühlte Temperatur": True,
    "Wettertext": True,
    "Wetter-Icons": True,
    "Tooltip-Bug": True,
    "Klick-Handler": True,
    "Warnungslogik": True,
    "Fortschrittsbalken": True,
    "Alarmfunktion": True,
    "Alarmtöne": True,
    "Feedbackformular": True,
    "Live-DWD-Ticker": True,
    "Wetterstudio-AI-Laufzeile": True,
    "Tornado-Center": True,
    "KI-Wetterberichte": False,
    "Wetterkarten-Generator": False,
    "TV-Modus": False,
    "Favoriten": False,
    "Smartphone-Version": False,
}